version: "3.8"
services:
  comic-shop:
    build: .
    ports:
      - 8081:8080
    environment:
      - DB_URL
      - DB_USER
      - DB_PASS
    container_name: comicshop-Container
    depends_on:
      - postgres
    volumes:
      - ./logs/application.log:/logs/application.log

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=p4ssw0rd
    container_name: postgres-container
    volumes:
      - db-data:/var/lib/postgresql/data
      
  promtail:
    image: grafana/promtail:latest
    container_name: comic-promtail
    volumes:
      - ./promtail/promtail-docker-config.yml:/etc/promtail/docker-config.yaml
      - ./logs/application.log:/var/log/application.log
    command: "--config.file=/etc/promtail/docker-config.yaml"
  loki:
    image: grafana/loki:latest
    container_name: comic-loki
    ports:
      - 3100:3100
  grafana:
    image: grafana/grafana:latest
    container_name: comic-grafana
    volumes:
      - grafana-data:/var/lib/grafana
    # persisting grafana settings
    ports:
      - 3000:3000
    depends_on:
      - loki
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    container_name: comic-prometheus
volumes:
  grafana-data:
    driver: local
  prometheus-data:
    driver: local
  db-data:
    driver: local